In [1]:
# Задания 1 - выполнено 2 - в процессе

In [2]:
#!pip install scikit-learn

In [3]:
import pandas as pd
import numpy as np
np.random.seed(42)

In [4]:
df = pd.read_csv("heart_disease.csv")

In [5]:
df

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4233,1,50,1.0,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,66.0,86.0,1
4234,1,51,3.0,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,65.0,68.0,0
4235,0,48,2.0,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1.0,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             4238 non-null   int64
 1   age              4238 non-null   int64
 2   education        4133 non-null   float64
 3   currentSmoker    4238 non-null   int64
 4   cigsPerDay       4209 non-null   float64
 5   BPMeds           4185 non-null   float64
 6   prevalentStroke  4238 non-null   int64
 7   prevalentHyp     4238 non-null   int64
 8   diabetes         4238 non-null   int64
 9   totChol          4188 non-null   float64
 10  sysBP            4238 non-null   float64
 11  diaBP            4238 non-null   float64
 12  BMI              4219 non-null   float64
 13  heartRate        4237 non-null   float64
 14  glucose          3850 non-null   float64
 15  TenYearCHD       4238 non-null   int64
dtypes: float64(9), int64(7)
memory usage: 529.9 KB

In [7]:
df = pd.read_csv("heart_disease.csv")
df_num = df.drop(['education', 'cigsPerDay', 'BPMeds', 'totChol','sysBP', 'diaBP',
                  'BMI', 'heartRate', 'glucose'], axis=1)

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

imp = SimpleImputer(missing_values=np.nan, strategy="median")
X = imp.fit_transform(df_num)
df_num = pd.DataFrame(X, columns=df_num.columns)
scale_colums = ['male', 'age', 'currentSmoker', 'prevalentStroke','prevalentHyp', 'diabetes', 'TenYearCHD']

scaler = StandardScaler()
scaler.fit(df_num[scale_colums])
df_num[scale_colums] = scaler.transform(df_num[scale_colums])
df_num

,male,age,currentSmoker,prevalentStroke,prevalentHyp,diabetes,TenYearCHD
0,1.153192,-1.234951,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305
1,-0.867158,-0.418257,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305
2,1.153192,-0.184916,1.011868,-0.077033,-0.671101,-0.162477,-0.423305
3,-0.867158,1.331800,1.011868,-0.077033,1.490089,-0.162477,2.362360
4,-0.867158,-0.418257,1.011868,-0.077033,-0.671101,-0.162477,-0.423305
...,...,...,...,...,...,...,...
4233,1.153192,0.048425,1.011868,-0.077033,1.490089,-0.162477,2.362360
4234,1.153192,0.165095,1.011868,-0.077033,-0.671101,-0.162477,-0.423305
4235,-0.867158,-0.184916,1.011868,-0.077033,-0.671101,-0.162477,-0.423305
4236,-0.867158,-0.651598,1.011868,-0.077033,-0.671101,-0.162477,-0.423305
4237,-0.867158,0.281766,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305

In [8]:
df_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             4238 non-null   float64
 1   age              4238 non-null   float64
 2   currentSmoker    4238 non-null   float64
 3   prevalentStroke  4238 non-null   float64
 4   prevalentHyp     4238 non-null   float64
 5   diabetes         4238 non-null   float64
 6   TenYearCHD       4238 non-null   float64
dtypes: float64(7)
memory usage: 231.9 KB

In [9]:
df_2 = pd.read_csv("heart_disease.csv")
df_cat = df_2.drop(['male', 'age', 'currentSmoker', 'prevalentStroke', 'prevalentHyp', 
                    'diabetes', 'TenYearCHD'], axis=1)

from sklearn.impute import SimpleImputer

imp = SimpleImputer(missing_values=np.nan, strategy="most_frequent")
imp.fit(df_cat)
X = imp.transform(df_cat)
df_cat = pd.DataFrame(X, columns=df_cat.columns)
df_cat

,education,cigsPerDay,BPMeds,totChol,sysBP,diaBP,BMI,heartRate,glucose
0,4.0,0.0,0.0,195.0,106.0,70.0,26.97,80.0,77.0
1,2.0,0.0,0.0,250.0,121.0,81.0,28.73,95.0,76.0
2,1.0,20.0,0.0,245.0,127.5,80.0,25.34,75.0,70.0
3,3.0,30.0,0.0,225.0,150.0,95.0,28.58,65.0,103.0
4,3.0,23.0,0.0,285.0,130.0,84.0,23.10,85.0,85.0
...,...,...,...,...,...,...,...,...,...
4233,1.0,1.0,0.0,313.0,179.0,92.0,25.97,66.0,86.0
4234,3.0,43.0,0.0,207.0,126.5,80.0,19.71,65.0,68.0
4235,2.0,20.0,0.0,248.0,131.0,72.0,22.00,84.0,86.0
4236,1.0,15.0,0.0,210.0,126.5,87.0,19.16,86.0,75.0
4237,2.0,0.0,0.0,269.0,133.5,83.0,21.47,80.0,107.0

In [10]:
df_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4238 entries, 0 to 4237
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   education   4238 non-null   float64
 1   cigsPerDay  4238 non-null   float64
 2   BPMeds      4238 non-null   float64
 3   totChol     4238 non-null   float64
 4   sysBP       4238 non-null   float64
 5   diaBP       4238 non-null   float64
 6   BMI         4238 non-null   float64
 7   heartRate   4238 non-null   float64
 8   glucose     4238 non-null   float64
dtypes: float64(9)
memory usage: 298.1 KB

In [11]:
df_cat_1 = df_cat['education']
df_cat_encoded, df_categories = df_cat_1.factorize()
df_cat_encoded

array([0, 1, 2, ..., 1, 2, 1], dtype=int64)

In [12]:
df_categories

Float64Index([4.0, 2.0, 1.0, 3.0], dtype='float64')

In [13]:
df_cat_2 = df_cat['cigsPerDay']
df_cat_encoded, df_categories = df_cat_2.factorize()
df_cat_encoded

array([0, 0, 1, ..., 1, 4, 0], dtype=int64)

In [14]:
df_categories

Float64Index([ 0.0, 20.0, 30.0, 23.0, 15.0,  9.0, 10.0,  5.0, 35.0, 43.0,  1.0,
              40.0,  3.0,  2.0, 12.0,  4.0, 18.0, 25.0, 60.0, 14.0, 45.0,  8.0,
              50.0, 13.0, 11.0,  7.0,  6.0, 38.0, 29.0, 17.0, 16.0, 19.0,
              70.0],
             dtype='float64')

In [15]:
df_cat_3 = df_cat['BPMeds']
df_cat_encoded, df_categories = df_cat_3.factorize()
df_cat_encoded

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [16]:
df_categories

Float64Index([0.0, 1.0], dtype='float64')

In [17]:
df_cat_4 = df_cat['sysBP']
df_cat_encoded, df_categories = df_cat_4.factorize()
df_cat_encoded

array([  0,   1,   2, ...,  11,  46, 164], dtype=int64)

In [18]:
df_categories

Float64Index([106.0, 121.0, 127.5, 150.0, 130.0, 180.0, 138.0, 100.0, 141.5,
              162.0,
              ...
              199.5, 101.5, 248.0,  99.5,  85.0, 230.0, 214.0, 192.5, 194.0,
              207.0],
             dtype='float64', length=234)

In [19]:
df_cat_5 = df_cat['diaBP']
df_cat_encoded, df_categories = df_cat_5.factorize()
df_cat_encoded

array([ 0,  1,  2, ..., 68, 41, 63], dtype=int64)

In [20]:
df_categories

Float64Index([ 70.0,  81.0,  80.0,  95.0,  84.0, 110.0,  71.0,  89.0, 107.0,
               76.0,
              ...
              110.5, 113.0,  53.0, 129.0,  52.0,  48.0,  56.0,  60.5, 115.5,
              127.5],
             dtype='float64', length=146)

In [21]:
df_cat_6 = df_cat['BMI']
df_cat_encoded, df_categories = df_cat_6.factorize()
df_cat_encoded

array([   0,    1,    2, ...,  255, 1090,  917], dtype=int64)

In [22]:
df_categories

Float64Index([26.97, 28.73, 25.34, 28.58,  23.1,  30.3, 33.11, 21.68, 26.36,
              23.61,
              ...
              32.47,  19.0, 20.85, 20.78, 36.07, 27.11, 30.48, 39.17,  26.7,
              43.67],
             dtype='float64', length=1363)

In [23]:
df_cat_7 = df_cat['heartRate']
df_cat_encoded, df_categories = df_cat_7.factorize()
df_cat_encoded

array([ 0,  1,  2, ..., 26, 30,  0], dtype=int64)

In [24]:
df_categories

Float64Index([ 80.0,  95.0,  75.0,  65.0,  85.0,  77.0,  60.0,  79.0,  76.0,
               93.0,  72.0,  98.0,  64.0,  70.0,  71.0,  62.0,  73.0,  90.0,
               96.0,  68.0,  63.0,  88.0,  78.0,  83.0, 100.0,  67.0,  84.0,
               57.0,  50.0,  74.0,  86.0,  55.0,  92.0,  66.0,  87.0, 110.0,
               81.0,  56.0,  89.0,  82.0,  48.0, 105.0,  61.0,  54.0,  69.0,
               52.0,  94.0, 140.0, 130.0,  58.0, 108.0, 104.0,  91.0,  53.0,
              106.0,  59.0,  51.0, 102.0, 107.0, 112.0, 125.0, 103.0,  44.0,
               47.0,  45.0,  97.0, 122.0, 120.0,  99.0, 115.0, 143.0, 101.0,
               46.0],
             dtype='float64')

In [25]:
df_cat_8 = df_cat['glucose']
df_cat_encoded, df_categories = df_cat_8.factorize()
df_cat_encoded

array([ 0,  1,  2, ..., 52, 12, 53], dtype=int64)

In [26]:
df_categories

Float64Index([ 77.0,  76.0,  70.0, 103.0,  85.0,  99.0,  78.0,  79.0,  88.0,
               61.0,
              ...
              368.0, 348.0, 248.0, 370.0, 193.0, 191.0, 256.0, 235.0, 210.0,
              260.0],
             dtype='float64', length=143)

In [27]:
df_cat_9 = df_cat['totChol']
df_cat_encoded, df_categories = df_cat_9.factorize()
df_cat_encoded

array([ 0,  1,  2, ..., 50, 59, 68], dtype=int64)

In [28]:
df_categories

Float64Index([195.0, 250.0, 245.0, 225.0, 285.0, 228.0, 205.0, 313.0, 260.0,
              254.0,
              ...
              337.0, 696.0, 363.0, 331.0, 361.0, 453.0, 347.0, 373.0, 385.0,
              119.0],
             dtype='float64', length=248)

In [29]:
new_df = pd.concat([df_num, df_cat_1, df_cat_2, df_cat_3, df_cat_4, df_cat_5,
                    df_cat_6, df_cat_7, df_cat_8, df_cat_9], axis=1)

In [30]:
new_df

,male,age,currentSmoker,prevalentStroke,prevalentHyp,diabetes,TenYearCHD,education,cigsPerDay,BPMeds,sysBP,diaBP,BMI,heartRate,glucose,totChol
0,1.153192,-1.234951,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,4.0,0.0,0.0,106.0,70.0,26.97,80.0,77.0,195.0
1,-0.867158,-0.418257,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,2.0,0.0,0.0,121.0,81.0,28.73,95.0,76.0,250.0
2,1.153192,-0.184916,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,1.0,20.0,0.0,127.5,80.0,25.34,75.0,70.0,245.0
3,-0.867158,1.331800,1.011868,-0.077033,1.490089,-0.162477,2.362360,3.0,30.0,0.0,150.0,95.0,28.58,65.0,103.0,225.0
4,-0.867158,-0.418257,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,3.0,23.0,0.0,130.0,84.0,23.10,85.0,85.0,285.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4233,1.153192,0.048425,1.011868,-0.077033,1.490089,-0.162477,2.362360,1.0,1.0,0.0,179.0,92.0,25.97,66.0,86.0,313.0
4234,1.153192,0.165095,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,3.0,43.0,0.0,126.5,80.0,19.71,65.0,68.0,207.0
4235,-0.867158,-0.184916,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,2.0,20.0,0.0,131.0,72.0,22.00,84.0,86.0,248.0
4236,-0.867158,-0.651598,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,1.0,15.0,0.0,126.5,87.0,19.16,86.0,75.0,210.0
4237,-0.867158,0.281766,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,2.0,0.0,0.0,133.5,83.0,21.47,80.0,107.0,269.0

In [31]:
new_df.to_csv('heart_disease_new.csv')

In [32]:
df = pd.read_csv("heart_disease_new.csv")

In [33]:
df = df.drop(['Unnamed: 0'], axis=1)

In [34]:
df

,male,age,currentSmoker,prevalentStroke,prevalentHyp,diabetes,TenYearCHD,education,cigsPerDay,BPMeds,sysBP,diaBP,BMI,heartRate,glucose,totChol
0,1.153192,-1.234951,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,4.0,0.0,0.0,106.0,70.0,26.97,80.0,77.0,195.0
1,-0.867158,-0.418257,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,2.0,0.0,0.0,121.0,81.0,28.73,95.0,76.0,250.0
2,1.153192,-0.184916,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,1.0,20.0,0.0,127.5,80.0,25.34,75.0,70.0,245.0
3,-0.867158,1.331800,1.011868,-0.077033,1.490089,-0.162477,2.362360,3.0,30.0,0.0,150.0,95.0,28.58,65.0,103.0,225.0
4,-0.867158,-0.418257,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,3.0,23.0,0.0,130.0,84.0,23.10,85.0,85.0,285.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4233,1.153192,0.048425,1.011868,-0.077033,1.490089,-0.162477,2.362360,1.0,1.0,0.0,179.0,92.0,25.97,66.0,86.0,313.0
4234,1.153192,0.165095,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,3.0,43.0,0.0,126.5,80.0,19.71,65.0,68.0,207.0
4235,-0.867158,-0.184916,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,2.0,20.0,0.0,131.0,72.0,22.00,84.0,86.0,248.0
4236,-0.867158,-0.651598,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,1.0,15.0,0.0,126.5,87.0,19.16,86.0,75.0,210.0
4237,-0.867158,0.281766,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,2.0,0.0,0.0,133.5,83.0,21.47,80.0,107.0,269.0

In [35]:
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(df, test_size=0.25, random_state=42)
train_set

,male,age,currentSmoker,prevalentStroke,prevalentHyp,diabetes,TenYearCHD,education,cigsPerDay,BPMeds,sysBP,diaBP,BMI,heartRate,glucose,totChol
3076,-0.867158,-0.768269,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,1.0,10.0,0.0,139.0,96.0,24.38,77.0,71.0,269.0
1187,1.153192,0.048425,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,1.0,20.0,0.0,114.0,64.0,22.32,85.0,71.0,261.0
3259,-0.867158,-1.468292,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,4.0,0.0,0.0,108.0,75.0,21.84,75.0,83.0,165.0
2823,1.153192,-0.184916,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,1.0,20.0,0.0,116.0,81.0,23.10,100.0,58.0,285.0
2031,-0.867158,1.681811,-0.988271,-0.077033,1.490089,-0.162477,2.362360,1.0,0.0,0.0,144.0,82.0,22.54,60.0,77.0,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3444,-0.867158,-1.584962,1.011868,-0.077033,1.490089,-0.162477,-0.423305,1.0,5.0,0.0,147.0,94.0,26.79,76.0,71.0,222.0
466,-0.867158,0.865118,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,3.0,15.0,0.0,125.0,74.0,21.08,80.0,72.0,250.0
3092,-0.867158,1.215129,-0.988271,-0.077033,1.490089,-0.162477,-0.423305,2.0,0.0,0.0,133.0,89.0,25.09,83.0,81.0,298.0
3772,1.153192,-1.234951,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,2.0,10.0,0.0,102.0,64.5,24.50,68.0,62.0,215.0
860,-0.867158,-1.701633,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,2.0,0.0,0.0,107.0,73.0,20.64,90.0,80.0,248.0

In [36]:
test_set

,male,age,currentSmoker,prevalentStroke,prevalentHyp,diabetes,TenYearCHD,education,cigsPerDay,BPMeds,sysBP,diaBP,BMI,heartRate,glucose,totChol
3188,1.153192,1.565141,-0.988271,-0.077033,1.490089,-0.162477,-0.423305,1.0,0.0,0.0,148.0,90.0,27.13,72.0,86.0,190.0
764,1.153192,-0.534928,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,3.0,0.0,0.0,125.0,89.0,27.98,85.0,83.0,162.0
3264,-0.867158,0.165095,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,1.0,2.0,0.0,127.0,81.0,20.24,75.0,96.0,261.0
1967,1.153192,-0.534928,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,3.0,30.0,0.0,126.0,89.5,28.68,75.0,92.0,250.0
2185,-0.867158,-0.534928,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,2.0,3.0,0.0,130.0,80.0,20.24,90.0,86.0,250.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2285,1.153192,-0.184916,-0.988271,-0.077033,1.490089,-0.162477,-0.423305,2.0,0.0,0.0,148.0,91.0,25.79,75.0,83.0,251.0
1833,-0.867158,-0.884939,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,3.0,0.0,0.0,129.0,85.5,31.84,95.0,74.0,256.0
3734,-0.867158,-0.534928,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,2.0,3.0,0.0,133.5,85.5,25.38,65.0,73.0,220.0
1411,-0.867158,-1.584962,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,3.0,0.0,0.0,114.5,72.0,24.11,85.0,75.0,295.0
2157,1.153192,0.515106,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,1.0,0.0,0.0,116.0,77.0,28.56,57.0,61.0,260.0

In [37]:
train_set.to_csv('hear_disease_train_clean.csv')

In [38]:
train_set = pd.read_csv("hear_disease_train_clean.csv")

In [39]:
train_set = train_set.drop(['Unnamed: 0'], axis=1)

In [40]:
train_set

,male,age,currentSmoker,prevalentStroke,prevalentHyp,diabetes,TenYearCHD,education,cigsPerDay,BPMeds,sysBP,diaBP,BMI,heartRate,glucose,totChol
0,-0.867158,-0.768269,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,1.0,10.0,0.0,139.0,96.0,24.38,77.0,71.0,269.0
1,1.153192,0.048425,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,1.0,20.0,0.0,114.0,64.0,22.32,85.0,71.0,261.0
2,-0.867158,-1.468292,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,4.0,0.0,0.0,108.0,75.0,21.84,75.0,83.0,165.0
3,1.153192,-0.184916,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,1.0,20.0,0.0,116.0,81.0,23.10,100.0,58.0,285.0
4,-0.867158,1.681811,-0.988271,-0.077033,1.490089,-0.162477,2.362360,1.0,0.0,0.0,144.0,82.0,22.54,60.0,77.0,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3173,-0.867158,-1.584962,1.011868,-0.077033,1.490089,-0.162477,-0.423305,1.0,5.0,0.0,147.0,94.0,26.79,76.0,71.0,222.0
3174,-0.867158,0.865118,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,3.0,15.0,0.0,125.0,74.0,21.08,80.0,72.0,250.0
3175,-0.867158,1.215129,-0.988271,-0.077033,1.490089,-0.162477,-0.423305,2.0,0.0,0.0,133.0,89.0,25.09,83.0,81.0,298.0
3176,1.153192,-1.234951,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,2.0,10.0,0.0,102.0,64.5,24.50,68.0,62.0,215.0
3177,-0.867158,-1.701633,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,2.0,0.0,0.0,107.0,73.0,20.64,90.0,80.0,248.0

In [41]:
train_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3178 entries, 0 to 3177
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             3178 non-null   float64
 1   age              3178 non-null   float64
 2   currentSmoker    3178 non-null   float64
 3   prevalentStroke  3178 non-null   float64
 4   prevalentHyp     3178 non-null   float64
 5   diabetes         3178 non-null   float64
 6   TenYearCHD       3178 non-null   float64
 7   education        3178 non-null   float64
 8   cigsPerDay       3178 non-null   float64
 9   BPMeds           3178 non-null   float64
 10  sysBP            3178 non-null   float64
 11  diaBP            3178 non-null   float64
 12  BMI              3178 non-null   float64
 13  heartRate        3178 non-null   float64
 14  glucose          3178 non-null   float64
 15  totChol          3178 non-null   float64
dtypes: float64(16)
memory usage: 397.4 KB

In [42]:
test_set.to_csv('hear_disease_test_clean.csv')

In [43]:
test_set = pd.read_csv("hear_disease_test_clean.csv")

In [44]:
test_set = test_set.drop(['Unnamed: 0'], axis=1)

In [45]:
test_set

,male,age,currentSmoker,prevalentStroke,prevalentHyp,diabetes,TenYearCHD,education,cigsPerDay,BPMeds,sysBP,diaBP,BMI,heartRate,glucose,totChol
0,1.153192,1.565141,-0.988271,-0.077033,1.490089,-0.162477,-0.423305,1.0,0.0,0.0,148.0,90.0,27.13,72.0,86.0,190.0
1,1.153192,-0.534928,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,3.0,0.0,0.0,125.0,89.0,27.98,85.0,83.0,162.0
2,-0.867158,0.165095,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,1.0,2.0,0.0,127.0,81.0,20.24,75.0,96.0,261.0
3,1.153192,-0.534928,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,3.0,30.0,0.0,126.0,89.5,28.68,75.0,92.0,250.0
4,-0.867158,-0.534928,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,2.0,3.0,0.0,130.0,80.0,20.24,90.0,86.0,250.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1055,1.153192,-0.184916,-0.988271,-0.077033,1.490089,-0.162477,-0.423305,2.0,0.0,0.0,148.0,91.0,25.79,75.0,83.0,251.0
1056,-0.867158,-0.884939,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,3.0,0.0,0.0,129.0,85.5,31.84,95.0,74.0,256.0
1057,-0.867158,-0.534928,1.011868,-0.077033,-0.671101,-0.162477,-0.423305,2.0,3.0,0.0,133.5,85.5,25.38,65.0,73.0,220.0
1058,-0.867158,-1.584962,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,3.0,0.0,0.0,114.5,72.0,24.11,85.0,75.0,295.0
1059,1.153192,0.515106,-0.988271,-0.077033,-0.671101,-0.162477,-0.423305,1.0,0.0,0.0,116.0,77.0,28.56,57.0,61.0,260.0

In [46]:
test_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1060 entries, 0 to 1059
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             1060 non-null   float64
 1   age              1060 non-null   float64
 2   currentSmoker    1060 non-null   float64
 3   prevalentStroke  1060 non-null   float64
 4   prevalentHyp     1060 non-null   float64
 5   diabetes         1060 non-null   float64
 6   TenYearCHD       1060 non-null   float64
 7   education        1060 non-null   float64
 8   cigsPerDay       1060 non-null   float64
 9   BPMeds           1060 non-null   float64
 10  sysBP            1060 non-null   float64
 11  diaBP            1060 non-null   float64
 12  BMI              1060 non-null   float64
 13  heartRate        1060 non-null   float64
 14  glucose          1060 non-null   float64
 15  totChol          1060 non-null   float64
dtypes: float64(16)
memory usage: 132.6 KB